# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 00:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('measurement_id', models.TextField(max_length=100)),
                ('sensor_batch_id', models.TextField(max_length=100)),
                ('glucose', models.FloatField()),
                ('insulin', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='measurement',
            unique_together=set([('user', 'measurement_id')]),
        ),
    ]
