# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-03 11:00
from __future__ import unicode_literals

import diabot.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('measurement_id', models.TextField(max_length=100)),
                ('sensor_batch_id', models.TextField(max_length=100)),
                ('glucose', models.FloatField()),
                ('insulin', models.FloatField()),
                ('tissue', models.TextField(verbose_name=diabot.models.TissueChoices)),
                ('mtype', models.TextField(verbose_name=diabot.models.MeasurementTypeChoices)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_id', models.TextField()),
                ('status', models.TextField(verbose_name=diabot.models.StatusChoices)),
                ('direction', models.TextField(verbose_name=diabot.models.DirectionChoices)),
                ('intervention', models.TextField(verbose_name=diabot.models.InterventionChoices)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='measurement',
            unique_together=set([('user', 'measurement_id')]),
        ),
    ]
